project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('posts/', include(('some.urls', 'posts'), namespace='posts')),

]

""" для работы ImageField """
if settings.DEBUG:  # FIXME
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # FIXME

project/some/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (
    Posts, Post, PostCreate, PostUpdate, post_comment, MyCommets, MyCommentsDelete, MyCommentDetail
)

urlpatterns = [
    path('', Posts.as_view(), name='posts'),
    path('<int:pk>', Post.as_view(), name='post'),
    path('create/', PostCreate.as_view(), name='postcreate'),
    path('<int:pk>/update', PostUpdate.as_view(), name='postupdate'),
    path('<int:pk>/comment', post_comment, name='postcomment'),
    path('comments/', MyCommets.as_view(), name='comments'),
    path('comments/<int:pk>', MyCommentDetail.as_view(), name='comment'),
    path('comments/<int:pk>/delete', MyCommentsDelete.as_view(), name='commentdelete'),
]

project/some/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class UserModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, db_column='Пользователь')

    def __str__(self):
        return f'{self.user}'


class PostModel(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=188, db_column='Заголовок')
    text = models.TextField(db_column='Текст')
    photo = models.ImageField(upload_to='image', null=True, blank=True, db_column='Фото', default='image/default.jpg')
    file = models.FileField(upload_to='video', null=True, blank=True, db_column='Видео/контент')
    time_in = models.DateTimeField(auto_now_add=True)
    # PA = 'Танки'
    # HP = 'Хилы'
    # DD = 'ДД'
    # TO = 'Торговцы'
    # GI = 'Гилдмастера'
    # KV = 'Квестгиверы'
    # KU = 'Кузнецы'
    # KO = 'Кожевники'
    # ZE = 'Зельевары'
    # MA = 'Мастера заклинаний'
    CHOICE = (
        ('PA', 'Танки'),
        ('HP', 'Хилы'),
        ('DD', 'ДД'),
        ('TO', 'Торговцы'),
        ('GI', 'Гилдмастера'),
        ('KV', 'Квестгиверы'),
        ('KU', 'Кузнецы'),
        ('KO', 'Кожевники'),
        ('ZE', 'Зельевары'),
        ('MA', 'Мастера заклинаний'),
    )
    category = models.CharField(max_length=2, choices=CHOICE)

    def get_absolute_url(self):
        return reverse('posts:post', args=[str(self.id)])

    def __str__(self):
        return f'{self.title} {self.text}'


class Comment(models.Model):
    post = models.ForeignKey(PostModel, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(db_column='Текст')
    time_in = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.text}'

project/templates/views_sites/comment.html
{% extends 'flatpages/default.html' %}
{% load custom_tags %}
{% block uname %}
<a class="navbar-brand" href="#!">{{ user.username }}</a>
{% endblock uname %}

{% block links %}
{% if request.user.is_authenticated %}
    <li class="nav-item"><a class="nav-link" href="{% url 'posts:postcreate' %}">Создать объяление</a></li>

{% endif %}
{% endblock links %}



{% block content %}
{% if comment %}


            <div class="card mb-4">
                <div class="card-body">
                    <div class="small text-muted">{{ comment.time_in }}</div>
                    <p class="card-text">{{ comment.text }}</p>
                    <li class="nav-item"><a class="nav-link" href="{% url 'posts:commentdelete' comment.id %}">Удалить</a></li>

                </div>
            </div>

{% endif %}
            {% endblock content %}

project/templates/views_sites/comments.html
{% extends 'flatpages/default.html' %}
{% load custom_tags %}
{% block uname %}
<a class="navbar-brand" href="#!">{{ user.username }}</a>
{% endblock uname %}

{% block links %}
{% if request.user.is_authenticated %}
    <li class="nav-item"><a class="nav-link" href="{% url 'posts:postcreate' %}">Создать объяление</a></li>

{% endif %}
{% endblock links %}



{% block content %}
{% if comments %}
{% for comment in comments %}

            <div class="card mb-4">
                <div class="card-body">
                    <div class="small text-muted">{{ comment.time_in }}</div>
                    <p class="card-text">{{ comment.text }}</p>
                    <li class="nav-item"><a class="nav-link" href="{% url 'posts:comment' comment.id %}">Подробнее</a></li>
                </div>
            </div>
            {% endfor %}
{% endif %}
            {% endblock content %}


{% block search %}
<form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {{ filterset.form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Найти" />
   </form>
{% endblock search %}



{% block Pagination %}
                    <nav aria-label="Pagination">
                        <hr class="my-0" />
                        <ul class="pagination justify-content-center my-4">
                            {% if page_obj.has_previous %}
                                <li class="page-item active" aria-current="page"><a class="page-link" href="?{% url_replace page=page_obj.previous_page_number %}">назад</a></li>
                            {% endif %}
                            {% if page_obj.has_previous %}
                                <li class="page-item active" aria-current="page"><a class="page-link" href="?{% url_replace page=1 %}">1</a></li>
                                {% if page_obj.previous_page_number != 1 %}
                                    <li class="page-item disabled"><a class="page-link" href="#!">...</a></li>
                                    <li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a></li>
                                {% endif %}
                            {% endif %}
                            <li class="page-item"><a class="page-link" href="">{{ page_obj.number }}</a></li>
                            {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a></li>
                                {% if paginator.num_pages != page_obj.next_page_number %}
                                    <li class="page-item disabled"><a class="page-link" href="#!">...</a></li>
                                    <li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a></li>
                                {% endif %}
                            {% endif %}
                            {% if page_obj.has_next %}
                                <li class="page-item active" aria-current="page"><a class="page-link" href="?{% url_replace page=page_obj.next_page_number %}">вперед</a></li>
                            {% endif %}

                        </ul>
                    </nav>
{% endblock Pagination %}

project/templates/views_sites/delete.html
{% extends 'flatpages/default.html' %}

{% block content %}

<h1>Удаление объявления</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем объявление - "{{ postdelete.text }}"?</p>
    <input type="submit" value="Delete"/>
</form>

{% endblock content %}

project/templates/views_sites/post.html
{% extends 'flatpages/default.html' %}

{% block content %}
{% if post %}

            <div class="card mb-4">
                {% if post.photo %}
                <a href="#!"><img class="card-img-top" src="{{ post.photo.url }}"
                                  alt="..."/></a>
                {% endif %}
                <div class="card-body">
                    <div class="small text-muted">{{ post.time_in }}</div>
                    <h2 class="card-title">{{ post.title }}</h2>
                    <h3 class="card-title">Категория - {{ post.get_category_display }} </h3>
                    <p class="card-text">{{ post.text }}</p>
                    <a class="btn btn-primary" href="{% url 'posts:posts' %}">Назад к объявления</a>
                    {% if request.user.is_authenticated %}
                    <a class="btn btn-primary" href="{% url 'posts:postupdate' post.id %}">Редактировать объявление</a>
                    <a class="btn btn-primary" href="{% url 'posts:postcomment' post.id %}">Перейти к откликам</a>
                    {% endif %}
                </div>
            </div>

{% endif %}

{% endblock content %}



project/templates/views_sites/post_comment.html
{% extends 'flatpages/default.html' %}

{% block content %}

<h1>Новый отклик</h1>
{% for comm in comment %}
Автор - {{ comm.user }} <br>
{{ comm.text }} <br><br>
{% endfor %}
<form action="" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Опубликовать">
</form>

{% endblock content %}



project/templates/views_sites/post_create.html
{% extends 'flatpages/default.html' %}

{% block content %}

<h1>Новое объявление</h1>
<form action="" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Опубликовать">
</form>

{% endblock content %}

project/templates/views_sites/posts.html
{% extends 'flatpages/default.html' %}

{% block uname %}
<a class="navbar-brand" href="#!">{{ user_name }}</a>
{% endblock uname %}

{% block links %}
{% if request.user.is_authenticated %}
    <li class="nav-item"><a class="nav-link" href="{% url 'posts:postcreate' %}">Создать объяление</a></li>

{% endif %}
{% endblock links %}



{% block content %}
{% if posts %}
{% for post in posts %}

            <div class="card mb-4">
                {% if post.photo %}
                <a href="#!"><img class="card-img-top" src="{{ post.photo.url }}"
                                  alt="..."/></a>
                {% endif %}
                <div class="card-body">
                    <div class="small text-muted">{{ post.time_in }}</div>
                    <h2 class="card-title">{{ post.title }}</h2>
                    <h3 class="card-title">Категория - {{ post.get_category_display }} </h3>
                    <p class="card-text">{{ post.text|truncatewords:5 }}</p>
                    <a class="btn btn-primary" href="{% url 'posts:post' post.id %}">Read more →</a>
                </div>
            </div>
            {% endfor %}
{% endif %}
            {% endblock content %}

{% block Pagination %}
                    <nav aria-label="Pagination">
                        <hr class="my-0" />
                        <ul class="pagination justify-content-center my-4">
                            {% if page_obj.has_previous %}
                                <li class="page-item active" aria-current="page"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">назад</a></li>
                            {% endif %}
                            {% if page_obj.has_previous %}
                                <li class="page-item active" aria-current="page"><a class="page-link" href="?page=1">1</a></li>
                                {% if page_obj.previous_page_number != 1 %}
                                    <li class="page-item disabled"><a class="page-link" href="#!">...</a></li>
                                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                                {% endif %}
                            {% endif %}
                            <li class="page-item"><a class="page-link" href="">{{ page_obj.number }}</a></li>
                            {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                                {% if paginator.num_pages != page_obj.next_page_number %}
                                    <li class="page-item disabled"><a class="page-link" href="#!">...</a></li>
                                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li>
                                {% endif %}
                            {% endif %}
                            {% if page_obj.has_next %}
                                <li class="page-item active" aria-current="page"><a class="page-link" href="?page={{ page_obj.next_page_number }}">вперед</a></li>
                            {% endif %}

                        </ul>
                    </nav>
{% endblock Pagination %}